name: Package React Native Version Bumper

on:
    push:
        branches:
            - main

jobs:
    package:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: "yarn"

            - name: Install dependencies
              run: yarn install

            - name: Compile extension
              run: yarn compile

            - name: Run lint
              run: yarn lint

            - name: Package extension
              run: yarn vsce package -o react-native-version-bumper.vsix

            - name: Upload VSIX artifact
              uses: actions/upload-artifact@v4
              with:
                  name: react-native-version-bumper-vsix
                  path: react-native-version-bumper.vsix
