name: Build & Release

on:
    push:
        branches: [main]
        tags: ['v*']
    pull_request:
        branches: [main]
    workflow_dispatch:
        inputs:
            deploy_to_marketplace:
                description: 'Deploy to VS Code Marketplace'
                required: false
                default: false
                type: boolean

jobs:
    build:
        name: Build & Package
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Bun
              uses: oven-sh/setup-bun@v1
              with:
                  bun-version: latest

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Install dependencies
              run: bun install

            - name: Lint
              run: bun run lint

            - name: Compile
              run: bun run compile

            - name: Package
              run: bun run package

            - name: Upload VSIX
              uses: actions/upload-artifact@v4
              with:
                  name: vsix-package
                  path: '*.vsix'

    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        needs: build
        if: startsWith(github.ref, 'refs/tags/v') || github.event.inputs.deploy_to_marketplace == 'true'
        environment: production

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Download VSIX
              uses: actions/download-artifact@v4
              with:
                  name: vsix-package

            - name: Deploy to VS Code Marketplace
              run: |
                  npm install -g @vscode/vsce
                  vsce publish --packagePath *.vsix
              env:
                  VSCE_PAT: ${{ secrets.VSCODE_MARKETPLACE_TOKEN }}

            - name: Deploy to Open VSX
              run: |
                  npm install -g ovsx
                  ovsx publish --packagePath *.vsix
              env:
                  OVSX_PAT: ${{ secrets.OPEN_VSX_TOKEN }}

            - name: Create GitHub Release
              if: startsWith(github.ref, 'refs/tags/v')
              uses: softprops/action-gh-release@v1
              with:
                  files: '*.vsix'
                  generate_release_notes: true
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
